on: push
name: deno@v1.6.3
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        deno: ['v1.6.3']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Deno ${{ matrix.deno }} test in ${{ matrix.os }}
    steps:
      # needed for deno fmt on windows
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: lint
        run: |
          deno fmt --check

      - name: test
        run: |
          deno test -A
